DROP DATABASE IF EXISTS REPORTAI;
CREATE DATABASE REPORTAI;
USE REPORTAI;

CREATE TABLE USUARIOS (
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	EMAIL VARCHAR(255) NOT NULL UNIQUE,
	SENHA VARCHAR(255) NOT NULL,
	NOME VARCHAR(255) NOT NULL,
	CPF CHAR(11) NOT NULL UNIQUE,
	DT_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE CATEGORIAS (
    ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    ICONE VARCHAR(50)
);

CREATE TABLE REGISTROS (
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	TITULO VARCHAR(255) NOT NULL,
	DESCRICAO TEXT NOT NULL,
    LOCALIZACAO VARCHAR(255),
	LATITUDE DECIMAL(10, 8),
    LONGITUDE DECIMAL(11, 8),
    DT_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DT_MODIFICACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    IS_CONCLUIDO BOOL DEFAULT FALSE,
    ID_CATEGORIA INT NOT NULL, FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS (ID),
    ID_USUARIO INT NOT NULL, FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS (ID)
);

CREATE TABLE IMAGENS (
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(255),
	CAMINHO TEXT,
	ID_REGISTRO INT NOT NULL, FOREIGN KEY (ID_REGISTRO) REFERENCES REGISTROS (ID)
);

CREATE TABLE INTERACOES (
	ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    TYPE ENUM('RELEVANTE', 'CONCLUIDO'),
	ID_USUARIO INT NOT NULL, FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS (ID),
	ID_REGISTRO INT NOT NULL, FOREIGN KEY (ID_REGISTRO) REFERENCES REGISTROS (ID)
);


